[package]
name = "sphere-image"
description = "Image decoding and texture cache for SphereGraphicEngine."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
sphere-core.workspace = true
image.workspace = true
thiserror.workspace = true
tracing.workspace = true
rustc-hash.workspace = true
